### ISSUE TITLE
Update to support beta-5 predicate calculation

### ISSUE THREAD

**Issue by dmihal** [FuelLabs/EVM-Wallet-Connector#14]
The predicate root calculation for beta-5 no longer uses chainId, therefore we need to update our code for calculating it.

However, instead of updating the code directly, we should import it from `@fuel-ts/predicate` as soon as https://github.com/FuelLabs/fuels-ts/issues/1646 is completed.

**Comment by dmihal** [comment]
@K1-R1 this is unblocked now that https://github.com/FuelLabs/fuels-ts/pull/1653 is merged.

Mind doing a quick update?

**Comment by K1-R1** [comment]
@dmihal I'll get it done
